<a href="https://colab.research.google.com/github/nassim1014/Pytorch-DeepLearning-Tuto/blob/main/Pytorch_DeepLearning_Tuto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch

Simple CNN model

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# Define the CNN architecture
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1)
        self.relu = nn.ReLU()
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)
        self.fc1 = nn.Linear(32 * 8 * 8, 256)  # Adjust based on the actual spatial dimensions

        self.fc2 = nn.Linear(256, 10)  # 10 output classes for example, change as needed

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.maxpool(x)

        # Print the size before fc1
        print(x.size())

        x = x.view(x.size(0), -1)
        print(x.size())  # Print the size before fc1

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x



# Download and prepare the CIFAR-10 dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers=2)

# Initialize the CNN model
net = SimpleCNN()

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# Training the CNN
for epoch in range(5):  # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data

        optimizer.zero_grad()

        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        if i % 2000 == 1999:  # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')


Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size([4, 2048])
torch.Size([4, 32, 8, 8])
torch.Size

what is a tensor : it s just like a list or a numpy array , when u do ML , u can use numpy array , when u use deep learning u use tensors . the diff is that they work better on GPU's (vs Regular CPU's)

In [7]:
import numpy as np

**Python Lists**

In [13]:
my_list = [[1,2,3,4],[7,8,5,1],[2,3,4,5]]
my_list

[[1, 2, 3, 4], [7, 8, 5, 1], [2, 3, 4, 5]]

**Numpy Array**

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.48889063, 0.40695538, 0.96426115, 0.11362705],
       [0.05249359, 0.98198358, 0.28733059, 0.81694207],
       [0.03696535, 0.2684262 , 0.52215465, 0.82389963]])

**TENSORS**

In [12]:
tensor_2d= torch.randn(3,4)
tensor_2d

tensor([[-0.7601,  0.4659,  0.8599,  0.2174],
        [-0.1338,  1.2879,  1.2660,  0.1226],
        [-0.7902,  2.3322,  1.6278, -1.5633]])

create tensor out of numpy array

In [16]:
torch.tensor(np1)

tensor([[0.4889, 0.4070, 0.9643, 0.1136],
        [0.0525, 0.9820, 0.2873, 0.8169],
        [0.0370, 0.2684, 0.5222, 0.8239]], dtype=torch.float64)

In [17]:
torch.zeros(3,4,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

**Create Basic Neural Net with Pytorch**

In [18]:
# Using the Iris Data set containing Irs Flowers - The goal classify the flowers
# this model will just take an input move it to the hidden layers and to the output and that s it no complicated stuff
import torch.nn as nn
import torch.nn.functional as F


In [21]:
#Create a Model Class that inherits nn.Module. NB : u can use functionnal programming to get things done quickely but here we re using Object oriented Programming

class Model(nn.Module):
    # input Layer (4 features of the flower)
    #   --> Hidden layer1 (number of neuronnes)
    #        --> Hideen Layer2
    #               --> output (3 classes of iris flower)
    def __init__(self, in_features =4 ,h1 = 8, h2 =9 ,out_feature=3) :
        super().__init__()
        # we have 4 features describing the flowers
        # we want first hidden layer with 8 neuronnes and a second hidden layer with 9
        # out_feature = 3 bc we have 3 classes
        self.fc1 = nn.Linear(in_features, h1) # from input layer to h1
        # fc := fully connected
        self.fc2 = nn.Linear(h1, h2)  # from h1 to h2
        self.out = nn.Linear(h2, out_feature) # from h2 to output
    #create a funciton that moves things forward from layer to another
    def forward(self , x):
        x=F.relu(self.fc1(x))
        x=F.relu(self.fc2(x))
        x= self.out(x)

        return x




In [22]:
torch.manual_seed(41)
# Create an instance of our model
model = Model()